baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Folgert Karsdorp"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
refLinksErrorLevel = "WARNING"
pygmentsUseClasses = true
publishDir = "docs"

[pagination]
  pagerSize = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#2E5D8A'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#2E5D8A"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap"
  fontFamilyHeading = "Atkinson Hyperlegible"
  fontFamilyParagraph = "Atkinson Hyperlegible"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Notebooks"
    identifier = "notebooks"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "Publications"
    url = "/references"
    weight = 10    